//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actualizacion_requisicion
    {
        public int id_requisicion { get; set; }
        public short estado_actualizacion { get; set; }
        public int encargado { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_notificacion { get; set; }
        public string medio_notificacion { get; set; }
    
        public virtual requisicion requisicion { get; set; }
        public virtual tipo_estado tipo_estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
