//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis_ProyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelsAnalisis : DbContext
    {
        public ModelsAnalisis()
            : base("name=ModelsAnalisis")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<requisicion> requisicions { get; set; }
        public virtual DbSet<rol_usuario> rol_usuario { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipo_estado> tipo_estado { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<actualizacion_requisicion> actualizacion_requisicion { get; set; }
        public virtual DbSet<correo> correos { get; set; }
        public virtual DbSet<telefono> telefonoes { get; set; }
    }
}
