//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correo
    {
        public int usuario { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public string direccion_correo { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
