//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requisicion()
        {
            this.actualizacion_requisicion = new HashSet<actualizacion_requisicion>();
        }
    
        public int id_requisicion { get; set; }
        public int comprador { get; set; }
        public int monto { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actualizacion_requisicion> actualizacion_requisicion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
